sergey_test:
    resource: "@SergeyTestBundle/Resources/config/routing.yml"
    prefix:   /

sergey_task:
    resource: "@SergeyTaskBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
